export const ActionTypes = {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
  SET_INGREDIENTS: 'SET_INGREDIENTS',
  FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',

  PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
  PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
  PURCHASE_BURGER_FAIL: 'PURCHASE_BURGER_FAIL',
  PURCHASE_INIT: 'PURCHASE_INIT',

  FETCH_ORDERS_START: 'FETCH_ORDERS_START',
  FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
  FETCH_ORDERS_FAIL: 'FETCH_ORDERS_FAIL'
};

export const authActionTypes = {
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_FAIL: 'AUTH_FAIL'
};
